server.port=8080
spring.application.name=qywx_server
qywx.callback.token=F1fcVoOYuEYw7Skq2mNseFnodi
qywx.callback.encoding-aes-key=OPgpWXSgGVhTPOHSpHAise6bPkqzYtmhNlxe2LwAnPA
qywx.callback.corp-id=ww0c7dd8c188047f58
